apiVersion: v1
kind: Service
metadata:
  name: echo-host
spec:
  selector:
    app: echo-host
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
